services:
  djangoapp:
    container_name: djangoapp
    build: .
    command: sh -c "python manage.py makemigrations authapp && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    ports:
      - "5460:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  tailwind:
    image: node:20-slim
    working_dir: /app
    # tty: true
    volumes:
      - .:/app
      - /app/node_modules 
    command: sh -c "npm install && npm run dev:css || tail -f /dev/null"
    depends_on:
      - djangoapp

volumes:
  postgres_data:
